# Generated by Django 3.2.5 on 2021-07-18 17:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(default='John', max_length=30)),
                ('last_name', models.CharField(default='Winchester', max_length=30)),
                ('job_function', models.CharField(default='Web Designer', max_length=80)),
                ('city', models.CharField(default='New York', max_length=20)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('jobs', models.PositiveIntegerField(default=0)),
                ('years_old', models.DateField(auto_now_add=True)),
                ('phone_number', models.PositiveBigIntegerField(blank=True, default=88888888888)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
                ('price_hourly', models.PositiveIntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
