# Generated by Django 3.2.5 on 2021-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountbase_years_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbase',
            name='years_old',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
